# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-JSON
version:      0.02
version_from: lib/DBIx/JSON.pm
installdirs:  site
requires:
    Carp:                          0
    DBI:                           1.15
    JSON::Syck:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
